/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface EpyButton {
    'disabled': boolean;
    'type': string;
  }
  interface EpyCard {
    'type': string;
  }
  interface EpyIcon {
    'icon': string;
  }
  interface EpyInput {
    'clear': boolean;
    'disabled': boolean;
    'errorLabel': string;
    'inputType': string;
    'label': string;
    'labelHelper': string;
    'maxlength': number;
    'minlength': number;
    'placeholder': string;
    'requiredLabel': string;
    'rows': number;
    'type': string;
    'validationStatus': string;
    'value': any;
  }
  interface EpyLoader {
    'type': string;
  }
  interface EpyPopover {
    'placement': any;
    'triggerEvent': string;
  }
}

declare global {


  interface HTMLEpyButtonElement extends Components.EpyButton, HTMLStencilElement {}
  var HTMLEpyButtonElement: {
    prototype: HTMLEpyButtonElement;
    new (): HTMLEpyButtonElement;
  };

  interface HTMLEpyCardElement extends Components.EpyCard, HTMLStencilElement {}
  var HTMLEpyCardElement: {
    prototype: HTMLEpyCardElement;
    new (): HTMLEpyCardElement;
  };

  interface HTMLEpyIconElement extends Components.EpyIcon, HTMLStencilElement {}
  var HTMLEpyIconElement: {
    prototype: HTMLEpyIconElement;
    new (): HTMLEpyIconElement;
  };

  interface HTMLEpyInputElement extends Components.EpyInput, HTMLStencilElement {}
  var HTMLEpyInputElement: {
    prototype: HTMLEpyInputElement;
    new (): HTMLEpyInputElement;
  };

  interface HTMLEpyLoaderElement extends Components.EpyLoader, HTMLStencilElement {}
  var HTMLEpyLoaderElement: {
    prototype: HTMLEpyLoaderElement;
    new (): HTMLEpyLoaderElement;
  };

  interface HTMLEpyPopoverElement extends Components.EpyPopover, HTMLStencilElement {}
  var HTMLEpyPopoverElement: {
    prototype: HTMLEpyPopoverElement;
    new (): HTMLEpyPopoverElement;
  };
  interface HTMLElementTagNameMap {
    'epy-button': HTMLEpyButtonElement;
    'epy-card': HTMLEpyCardElement;
    'epy-icon': HTMLEpyIconElement;
    'epy-input': HTMLEpyInputElement;
    'epy-loader': HTMLEpyLoaderElement;
    'epy-popover': HTMLEpyPopoverElement;
  }
}

declare namespace LocalJSX {
  interface EpyButton {
    'disabled'?: boolean;
    'onOnClick'?: (event: CustomEvent<any>) => void;
    'type'?: string;
  }
  interface EpyCard {
    'type'?: string;
  }
  interface EpyIcon {
    'icon'?: string;
  }
  interface EpyInput {
    'clear'?: boolean;
    'disabled'?: boolean;
    'errorLabel'?: string;
    'inputType'?: string;
    'label'?: string;
    'labelHelper'?: string;
    'maxlength'?: number;
    'minlength'?: number;
    'onOnChange'?: (event: CustomEvent<any>) => void;
    'placeholder'?: string;
    'requiredLabel'?: string;
    'rows'?: number;
    'type'?: string;
    'validationStatus'?: string;
    'value'?: any;
  }
  interface EpyLoader {
    'type'?: string;
  }
  interface EpyPopover {
    'placement'?: any;
    'triggerEvent'?: string;
  }

  interface IntrinsicElements {
    'epy-button': EpyButton;
    'epy-card': EpyCard;
    'epy-icon': EpyIcon;
    'epy-input': EpyInput;
    'epy-loader': EpyLoader;
    'epy-popover': EpyPopover;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'epy-button': LocalJSX.EpyButton & JSXBase.HTMLAttributes<HTMLEpyButtonElement>;
      'epy-card': LocalJSX.EpyCard & JSXBase.HTMLAttributes<HTMLEpyCardElement>;
      'epy-icon': LocalJSX.EpyIcon & JSXBase.HTMLAttributes<HTMLEpyIconElement>;
      'epy-input': LocalJSX.EpyInput & JSXBase.HTMLAttributes<HTMLEpyInputElement>;
      'epy-loader': LocalJSX.EpyLoader & JSXBase.HTMLAttributes<HTMLEpyLoaderElement>;
      'epy-popover': LocalJSX.EpyPopover & JSXBase.HTMLAttributes<HTMLEpyPopoverElement>;
    }
  }
}


