/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface EpyButton {
    'epyclass': string;
  }
  interface EpyCard {
    'epyclass': string;
  }
  interface EpyLoader {
    'epyclass': string;
  }
}

declare global {


  interface HTMLEpyButtonElement extends Components.EpyButton, HTMLStencilElement {}
  var HTMLEpyButtonElement: {
    prototype: HTMLEpyButtonElement;
    new (): HTMLEpyButtonElement;
  };

  interface HTMLEpyCardElement extends Components.EpyCard, HTMLStencilElement {}
  var HTMLEpyCardElement: {
    prototype: HTMLEpyCardElement;
    new (): HTMLEpyCardElement;
  };

  interface HTMLEpyLoaderElement extends Components.EpyLoader, HTMLStencilElement {}
  var HTMLEpyLoaderElement: {
    prototype: HTMLEpyLoaderElement;
    new (): HTMLEpyLoaderElement;
  };
  interface HTMLElementTagNameMap {
    'epy-button': HTMLEpyButtonElement;
    'epy-card': HTMLEpyCardElement;
    'epy-loader': HTMLEpyLoaderElement;
  }
}

declare namespace LocalJSX {
  interface EpyButton {
    'epyclass'?: string;
    'onClickButton'?: (event: CustomEvent<any>) => void;
  }
  interface EpyCard {
    'epyclass'?: string;
  }
  interface EpyLoader {
    'epyclass'?: string;
  }

  interface IntrinsicElements {
    'epy-button': EpyButton;
    'epy-card': EpyCard;
    'epy-loader': EpyLoader;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'epy-button': LocalJSX.EpyButton & JSXBase.HTMLAttributes<HTMLEpyButtonElement>;
      'epy-card': LocalJSX.EpyCard & JSXBase.HTMLAttributes<HTMLEpyCardElement>;
      'epy-loader': LocalJSX.EpyLoader & JSXBase.HTMLAttributes<HTMLEpyLoaderElement>;
    }
  }
}


